from __future__ import annotations

import difflib
import re
from typing import Any

from jarvis_v2.agent.types import ToolResult
from jarvis_v2.tools.capabilities import describe_capabilities
from jarvis_v2.v3_commands import (
    V3_DASHBOARD_COMMAND,
    V3_DASHBOARD_INFO_COMMAND,
    V3_DIAGNOSE_PYTHON_COMMAND,
    V3_DIAGNOSE_PYTHON_JSON_COMMAND,
    V3_ONE_SHOT_TIME_COMMAND,
)

LOCAL_PATH_RE = re.compile(r"/(?:Users|private|var/folders|tmp)/[^\n\r;]*")


HELP_SECTIONS = {
    "core": [
        "jarvis status",
        "jarvis doctor",
        "priority goal",
        "harness status",
        "harness doctrine",
        "coding discipline: improve Jarvis recovery tests",
        "harness completion",
        "completion audit",
        "evidence ledger",
        "completion claim gate",
        "completion next proof",
        "completion proof refresh",
        "operator handoff",
        "harness readiness digest",
        "execution proof bundle: organize downloads; verification list changed files; tests smoke passed; evidence recent run ok; recovery stop on mismatch",
        "execution mission control: organize downloads and summarize what changed",
        "execution case handoff: organize downloads and summarize what changed",
        "save execution case: organize downloads and summarize what changed",
        "case evidence packet latest: verification receipt 12 confirmed changed files",
        "case evidence latest: verification receipt 12 confirmed changed files",
        "execution case latest",
        "execution case gate",
        "execution case review",
        "execution case closure",
        "execution case timeline",
        "execution runbook: organize downloads and summarize what changed",
        "agi gates",
        "agi next build move",
        "agi next build move: personal integrations",
        "harness cycle: organize my desktop and summarize what changed",
        "harness lifecycle: inspect my screen and summarize what changed",
        "harness control: organize downloads and summarize what changed",
        "command cockpit: organize downloads and summarize what changed",
        "execution governor: organize downloads and summarize what changed",
        "harness operations",
        "architecture map",
        "brain loop",
        "roadmap",
        "model routing status",
        "specialist router contract: summarize this work and propose the next code test",
        "specialist orchestration packet: summarize this work and propose the next code test",
        "specialist route quality: summarize this work and propose the next code test",
        "specialist execution readiness: fix this code bug and run focused tests",
        "specialist handoff receipt: fix this code bug and run focused tests",
        "specialist handoff quality gate: summarize this work history into a brief",
        "specialist proposal gate: fix this code bug and run focused tests",
        "specialist model draft: summarize this work history into a brief",
        "specialist tool dry run: summarize memory; tool brain_search; args query=Jarvis harness; verification cites local memory only",
        "specialist execution handoff: summarize memory; tool brain_search; args query=Jarvis harness; verification cites local memory only",
        "specialist post-run closure: summarize memory; tool brain_search; args query=Jarvis harness; verification cites local memory only; runtime_trace trace reviewed; runtime_trace_sha256 <hash>; verification_receipt receipt reviewed; verification_receipt_sha256 <hash>; audit audit reviewed; audit_sha256 <hash>; recovery recovery reviewed; recovery_sha256 <hash>; learning learning reviewed; learning_sha256 <hash>; completion_claim claim reviewed; completion_claim_sha256 <hash>",
        "specialist cycle ledger: summarize memory; tool brain_search; args query=Jarvis harness; verification cites local memory only; runtime_trace reviewed; runtime_trace_sha256 <hash>; verification_receipt reviewed; verification_receipt_sha256 <hash>; audit reviewed; audit_sha256 <hash>; recovery reviewed; recovery_sha256 <hash>; learning reviewed; learning_sha256 <hash>; completion_claim reviewed; completion_claim_sha256 <hash>",
        "model planner prompt preview: find files README in .",
        "capability map",
        "tool search: approvals",
        "tool detail: run_shell_command",
        "risk matrix",
        "command diagnosis: run command python3 --version",
        f"terminal one-shot: {V3_DIAGNOSE_PYTHON_JSON_COMMAND}",
        f"terminal one-shot: {V3_ONE_SHOT_TIME_COMMAND}",
        f"terminal dashboard: {V3_DASHBOARD_COMMAND}",
        f"terminal dashboard help: {V3_DASHBOARD_INFO_COMMAND}",
        "help safety",
        "stop Jarvis",
        "status dashboard",
        "catch me up",
        "focus brief",
        "safe next actions",
        "next action packet",
        "mission control",
        "daily plan",
        "list tools goals",
        "recent tool runs",
        "verification receipt",
        "runtime trace receipt",
        "execution audit gate",
        "execution health report",
        "recovery closure checklist",
        "execution learning closure",
        "after-action learning packet",
        "export state",
    ],
    "control": [
        "capability map",
        "capability cockpit",
        "cockpit",
        "channel health",
        "trust checklist",
        "earned trust checklist",
        "why should I trust Jarvis",
        "jarvis status",
        "status dashboard",
        "readiness report",
        "safety status",
        "risk matrix",
        "completion claim gate",
        "subagent fleet status",
        "internal orchestration",
        "agent status",
        "worker status",
        "Use this topic when you want the visible control plane: what Jarvis can do, why a lane has earned trust, what is healthy, what is blocked, what needs approval, and which internal workers are ready.",
        "Every command in this topic is READ_ONLY. It does not approve, send, call, execute tools, read private data, control the computer, or change state.",
        "For failed sends/calls, start with `channel health`; for overall readiness, start with `capability cockpit`; for trust evidence, start with `trust checklist`; for completion claims, start with `completion claim gate`.",
    ],
    "safety": [
        "safety status",
        "privacy report",
        "readiness report",
        "prototype readiness",
        "frozen routing risk report",
        "planner input guard report",
        "setup check",
        "storage status",
        "storage recovery plan",
        "storage recovery check",
        "voice setup check",
        "voice stop intent: stop listening",
        "computer control status",
        "risk preflight: run a script and email me the result",
        "risky request lifecycle: run a script and email me the result",
        "action readiness: run a script and email me the result",
        "execution contract: organize my downloads and summarize what changed",
        "argument contract: run command python3 --version",
        "verification packet: organize my downloads and summarize what changed",
        "acceptance gate: organize my downloads; evidence recent tool run ok; tests smoke passed",
        "command intake: organize my downloads and summarize what changed",
        "command cockpit: organize my downloads and summarize what changed",
        "command diagnosis: run command python3 --version",
        "execution governor: organize my downloads and summarize what changed",
        "execution mission control: organize my downloads and summarize what changed",
        "execution case handoff: organize my downloads and summarize what changed",
        "save execution case: organize my downloads and summarize what changed",
        "case evidence packet latest: approval readiness, approval packet, and approval chain proof reviewed",
        "case evidence latest: approval readiness, approval packet, and approval chain proof reviewed; verification receipt linked",
        "execution case latest",
        "execution case gate",
        "execution case review",
        "execution case closure",
        "execution case timeline",
        "execution runbook: organize my downloads and summarize what changed",
        "execution readiness matrix: organize my downloads and summarize what changed",
        "dispatch decision: organize my downloads and summarize what changed",
        "planner gap: organize my downloads and summarize what changed",
        "second loop: organize my desktop and summarize what changed",
        "second loop packet: organize my desktop and summarize what changed",
        "rehearse: run command python3 --version",
        f"terminal diagnose: {V3_DIAGNOSE_PYTHON_COMMAND}",
        f"terminal send: {V3_ONE_SHOT_TIME_COMMAND}",
        "approval review",
        "save approval review",
        "capability map safety",
        "architecture map",
        "autonomy plan: organize my desktop and summarize the result",
        "risky request lifecycle: use my computer to inspect the screen",
        "Jarvis auto-runs only read-only and local-safe tools.",
        "High-risk actions require explicit approval and enter the pending approval queue.",
        "Personal-data and computer-control actions are approval-gated.",
        "Brain-dump organizing only writes Jarvis memory/Obsidian records.",
        "Use pending approvals, approval readiness <id|latest>, approval packet <id|latest>, approval chain proof <id|latest>, approve approval <id|latest>, and dismiss approval <id|latest>.",
        "Approval is rejected until approval readiness and the matching last-look approval packet have been viewed; approval chain proof then links approval to the approved rerun and verification receipt.",
    ],
    "approvals": [
        "pending approvals",
        "approval summary",
        "approval review",
        "approval history",
        "approval chain proof <id|latest>",
        "approval readiness <id|latest>",
        "approval detail <id|latest>",
        "approval packet <id|latest>",
        "save approval review",
        "approve approval <id|latest>",
        "dismiss approval <id|latest>",
        "Run approval readiness first, then the approval packet as the required last-look preview, then approval chain proof before trusting blocked shell, clipboard, file, reminder, or computer-control reruns.",
        "Approve commands only rerun after readiness and the matching approval packet have been viewed.",
    ],
    "continuity": [
        "return brief",
        "save return brief",
        "handoff brief",
        "save handoff brief",
        "session closeout",
        "save session closeout",
        "work queue",
        "save work queue",
        "build progress",
        "build delta",
        "work block checkpoint",
        "operator timebox: continue Jarvis stop_at=2026-06-09T08:10:00+09:00 current_time=2026-06-08T20:55:00+09:00 timezone=Asia/Seoul",
        "operator instruction supersession: previous=<older instruction> latest=<newer instruction> stop_at=<ISO> current_time=<ISO>",
        "checkpoint recovery cockpit: continue Jarvis V2 safely stop_at=2026-06-09T08:10:00+09:00 current_time=2026-06-08T20:55:00+09:00 timezone=Asia/Seoul",
        "checkpoint recovery",
        "checkpoint recovery apply",
        "checkpoint recovery receipt",
        "checkpoint recovery execute reviewed=true step=<reviewed local-safe step> verification=<evidence>",
        "checkpoint recovery follow-through: step=<reviewed local-safe step> verification=<evidence> receipt=<receipt path> receipt_sha256=<hash> checkpoint=<checkpoint path> checkpoint_sha256=<hash> stop=<stop condition>",
        "autonomy resume gate: stop_at=<ISO> current_time=<ISO> step=<reviewed local-safe step> verification=<evidence> receipt=<path> receipt_sha256=<hash> checkpoint=<path> checkpoint_sha256=<hash> stop_condition=<condition>",
        "autonomy continuation execution: stop_at=<ISO> current_time=<ISO> step=<reviewed local-safe recovery> verification=<evidence> receipt=<path> receipt_sha256=<hash> checkpoint=<path> checkpoint_sha256=<hash> stop_condition=<condition> next_step=<one local-safe step> next_verification=<evidence> prior_cycle_ledger_token_sha256=<optional prior proof hash>",
        "autonomy step closure: stop_at=<ISO> current_time=<ISO> step=<completed local-safe step> post_step_verification=<evidence> post_step_receipt_path=<path> post_step_receipt_sha256=<hash> post_step_checkpoint_path=<path> post_step_checkpoint_sha256=<hash> execution_health=<health> execution_audit=<audit> after_action_learning=<learning> prior_cycle_ledger_token_sha256=<optional prior proof hash>",
        "autonomy cycle ledger: stop_at=<ISO> current_time=<ISO> step=<completed local-safe step> verification=<evidence> receipt=<path> checkpoint=<path> next_step=<one local-safe step> next_verification=<evidence> post_step_verification=<evidence> post_step_receipt_path=<path> post_step_receipt_sha256=<hash> post_step_checkpoint_path=<path> post_step_checkpoint_sha256=<hash> prior_cycle_ledger_token_sha256=<optional prior proof hash>",
        "save build progress",
        "save build delta",
        "save work block checkpoint",
        "recent saved notes",
        "I'm back",
        "what did I miss",
        "focus brief: build Jarvis safely",
        "work session packet: build Jarvis safely",
        "next session plan: continue Jarvis safely",
        "resume plan",
        "start work session",
        "catch me up",
        "safe next actions",
        "next action packet",
        "what should I do now",
        "send me a priority card",
        "what's my next move",
        "priority stack",
        "continuation packet: continue Jarvis V2 safely",
        "build target packet: continue Jarvis V2 safely",
        "harness build slice: personal connector readiness",
        "save build target packet: continue Jarvis V2 safely",
        "what should Jarvis do next?",
        "mission control",
        "recent activity",
        "what changed while I was gone",
        "what changed in Jarvis",
        "activity digest",
    ],
    "memory": [
        "remember that ...",
        "search memory for ...",
        "what do you remember",
        "feedback: Jarvis should explain approvals more clearly",
        "feedback report",
        "save feedback report",
        "feedback actions",
        "save feedback actions",
        "failure to test: Jarvis overlapped dashboard text",
        "failure clusters",
        "failure promotion packet",
        "failure implementation packet: layout",
        "failure apply contract: layout",
        "failure learning cockpit: layout",
        "failure patch receipt: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>",
        "failure patch application bridge: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract",
        "failure patch completion gate: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract",
        "failure patch handoff: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract",
        "failure patch closeout: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract; completion audit reviewed; evidence ledger reviewed; completion claim gate reviewed; review post-claim review complete",
        "failure learning record: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract; completion audit reviewed; evidence ledger reviewed; completion claim gate reviewed; review post-claim review complete; after-action learning reviewed; record target learning review; regression smoke_test_status_server_layout linked; durability checkpoint saved; learning record sha256 <hash>",
        "failure learning closure ledger: layout; changed files jarvis_v2/scripts/smoke_test_status_server.py; test first pre-patch failing assertion reviewed; verification python3 -m jarvis_v2.scripts.smoke_test_status_server passed; compile python3 -m compileall -q jarvis_v2 passed; rollback scoped test assertion; patch receipt sha256 <hash>; contract apply contract reviewed; application bridge applied patch bound to contract; completion audit reviewed; evidence ledger reviewed; completion claim gate reviewed; review post-claim review complete; after-action learning reviewed; record target learning review; regression smoke_test_status_server_layout linked; durability checkpoint saved; learning record sha256 <hash>",
        "learning review",
        "save learning review",
        "queue learning tasks",
        "session learning preview",
        "after-action learning packet",
        "execution health report",
        "recovery closure checklist",
        "execution learning closure",
        "organize brain dump: task: ...; remember: ...",
        "list jarvis notes",
        "list jarvis notes in Projects",
        "search jarvis notes for ...",
        "outline jarvis note Projects/Idea",
        "summarize jarvis note Projects/Idea",
        "read jarvis note Projects/Note Name",
        "create jarvis note Projects/Idea: ...",
        "append jarvis note Projects/Idea: ...",
        "save jarvis note Projects/Idea: ...",
        "save to jarvis notes: ...",
        "write this down: ...",
        "write down: ...",
        "take a note: ...",
        "make note of ...",
        "note to self: ...",
        "show my notes",
        "ingest inbox",
        "recent file digest",
        "add profile note ...",
        "read profile",
    ],
    "organize": [
        "organize brain dump: task: review notes; remember: the operator likes direct updates",
        "process note: goal: Build Jarvis | full assistant | this month",
        "capture brain dump: decision: Keep approvals | safety | high-risk stays blocked",
    ],
    "preferences": [
        "set preference response style to direct and warm category communication",
        "preferences",
        "show preference response style",
        "preference 1 retired",
        "all preferences",
    ],
    "people": [
        "add person <name> relation <relation> notes <notes>",
        "people",
        "show person <name>",
        "log interaction with <name>: <summary>",
    ],
    "goals": [
        "create goal <title> because <purpose> by <horizon>",
        "new goal get fit because health",
        "show my goals",
        "what goals do I have",
        "add step to goal 1: ...",
        "complete goal step 2",
        "goal 1 status",
        "next actions",
        "what are my next actions",
    ],
    "tasks": [
        "add task ...",
        "add task ... due Friday priority high",
        "preview tasks from jarvis note Projects/Plan",
        "import tasks from jarvis note Projects/Plan",
        "import tasks from note Projects/Plan priority high",
        "tasks",
        "show my tasks",
        "todo list",
        "what do I need to do",
        "add todo buy milk",
        "tasks due today",
        "what's due tomorrow",
        "today's tasks",
        "completed tasks",
        "overdue tasks",
        "show high priority tasks",
        "urgent tasks",
        "task overview",
        "task board",
        "todo board",
        "next task",
        "show next task",
        "what is my next task",
        "show task 1",
        "task completion packet 1",
        "search tasks approval",
        "set task 1 priority high",
        "set task 1 due Friday",
        "rename task 1: review Jarvis queue",
        "complete task 1 with evidence: verified in recent tool runs",
        "complete task 1",
        "pause task 1",
        "reopen task 1",
        "drop task 1",
        "set task 1 to paused",
        "export tasks",
    ],
    "decisions": [
        "record decision <choice> because <reason> impact <result>",
        "decisions",
        "show decision 1",
        "decision 1 superseded",
        "all decisions",
    ],
    "conversation": [
        "assistant turn rehearsal: can we talk about memory?",
        "chat loop preview: use my computer to organize files",
        "chat continuity brief",
        "chat response health",
        "chat safety",
        "chat context: what should Jarvis do next?",
        "chat prompt preview: how should Jarvis talk about memory?",
        "save chat context: how should Jarvis use memory?",
        "rehearse: get clipboard",
        "recent conversation",
        "search conversations for ...",
        "session learning preview",
        "summarize this session",
        "draft skill from this session called <name>",
    ],
    "skills": [
        "skill match preview: import notes into memory",
        "extract linked skills from https://github.com/multica-ai/andrej-karpathy-skills.git https://github.com/NousResearch/hermes-agent https://github.com/tinyhumansai/openhuman",
        "install linked skills from andrej-karpathy-skills hermes-agent openhuman",
        "save skill <name> when <trigger> do <procedure>",
        "search skills memory",
        "get skill <name>",
        "list skills",
        "delete skill <name>",
    ],
    "personal": [
        "integration status",
        "integration readiness",
        "integration readiness: calendar",
        "integration execution matrix",
        "integration execution matrix: email",
        "integration adapter manifest",
        "integration adapter manifest: email",
        "integration adapter probe: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only",
        "integration adapter acceptance: email",
        "integration contract: email",
        "integration action preview: email -> send draft reply",
        "integration scope packet: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only",
        "integration dry run contract: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only",
        "integration runbook: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft",
        "integration promotion gate: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft; tests blocked send smoke; audit tool run receipt",
        "integration implementation spec: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft; tests blocked send smoke; audit tool run receipt",
        "integration preflight contract: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft; tests blocked send smoke; audit tool run receipt",
        "integration enablement gate: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft; tests blocked send smoke; audit tool run receipt; acceptance gate passed",
        "integration rehearsal receipt: email -> send draft reply; target thread; time today; data draft-only; verification confirm not sent; rollback discard draft; tests blocked send smoke; audit tool run receipt; acceptance gate passed",
        "integration metadata preview: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only; tests blocked full body smoke; audit metadata preview receipt; acceptance gate passed",
        "integration proof bundle: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only; rollback no connector call; tests adapter acceptance passed; audit adapter acceptance receipt; acceptance gate passed",
        "integration implementation review: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only; rollback no connector call; tests adapter acceptance passed; audit adapter acceptance receipt; acceptance gate passed; status status api smoke passed",
        "integration route lock: email -> search mailbox metadata; target inbox; time last 7 days; data metadata-only; verification fake rows only; rollback no connector call; tests adapter acceptance passed; audit adapter acceptance receipt; acceptance gate passed; status status api smoke passed",
        "legacy connector migration audit",
        "integration migration plan: calendar",
        "integration migration plan: email",
        "integration migration plan: messages",
        "translate hello to Korean",
        "how do you say thank you in Korean",
        "what is 사랑 in English",
        "convert 100 USD to KRW",
        "weather in Tokyo",
        "news about Korea",
        "what is bitcoin worth",
        "stock price of AAPL",
        "remind me to review Jarvis integrations",
        "open Jarvis vault",
        "Personal-data reads and outside-world actions need explicit approval.",
    ],
    "info": [
        "weather in Tokyo",
        "what time is it in Seoul",
        "time in Tokyo",
        "Tokyo time",
        "current time Seoul",
        "news about Korea",
        "air quality in Seoul",
        "sunrise in Tokyo",
        "this day in history",
        "today in history",
        "next holidays in Korea",
        "tell me about Ada Lovelace",
        "wiki Ada Lovelace",
        "what is photosynthesis",
        "define serendipity",
        "dictionary serendipity",
        "look up the definition of serendipity",
        "what is the meaning of serendipity",
        "Info lookups are LOCAL_SAFE when they use public data; private accounts still require approval.",
    ],
    "productivity": [
        "what's on my calendar today",
        "what is on my schedule today",
        "what am I doing today",
        "schedule today",
        "show my calendar today",
        "am I free tomorrow afternoon",
        "free today",
        "read recent emails",
        "email from Sam",
        "what emails did Sam send me",
        "tasks due today",
        "what is my next task",
        "show alarms",
        "remind me to review Jarvis at 5pm",
        "set a reminder to call Sam at 5pm",
        "remind me to call Sam when I get home",
        "set a timer for 10 minutes",
        "timer 10m",
        "alarm 7am",
        "schedule lunch tomorrow at noon",
        "Calendar edits, sends, and reminders/timers that affect the outside world stay approval-aware.",
    ],
    "utilities": [
        "translate hello to Korean",
        "convert 100 USD to KRW",
        "convert 10 km to miles",
        "what is 10 pounds in kg",
        "how many kg is 10 pounds",
        "how many cups in a liter",
        "time in Tokyo",
        "Tokyo time",
        "what time zone am I in",
        "time difference between Seoul and London",
        "what date is tomorrow",
        "what date is in two days",
        "what day is next Friday",
        "days until Christmas",
        "days until Thanksgiving",
        "how many weeks until Christmas",
        "countdown Halloween",
        "when is Christmas",
        "when is MLK Day",
        "when is Thanksgiving",
        "calculate 18% of 240",
        "percentage change from 50 to 60",
        "total with 18% tip on 240",
        "total with 8% tax on 100",
        "split bill 240 3 ways",
        "bmi 70 kg 180 cm",
        "generate a 16 character password",
        "generate a 16 character password without symbols",
        "generate uuid",
        "add 15 and 20",
        "divide 84 by 3",
        "12 times 8",
        "spell restaurant",
        "word count hello world",
        "letter count restaurant",
        "uppercase hello world",
        "uppercase the phrase hello world",
        "convert hello world to snake case",
        "camel case hello world",
        "initials the operator",
        "what are the initials of the operator",
        "slugify hello world",
        "repeat hello 3 times",
        "Utilities are mostly LOCAL_SAFE; Jarvis still avoids secrets or sensitive text in public services.",
    ],
    "research": [
        "research Zoey OS",
        "research local-first AI note taking",
        "web lookup OpenClaw agent safety",
        "look up OpenAI model context windows",
        "web search for Jarvis agent safety patterns",
        "fetch page https://example.com",
        "recent browser pages",
        "summarize latest page",
        "Research & Web can look up public sources, search the web, fetch pages, and summarize fetched pages. It does not send messages, approve requests, read private accounts, write notes, or change external state from the help/capability surfaces. Fetching, link extraction, and search may save fetched pages to local browser history; they have no automatic mutation contract for other local state.",
    ],
    "writing": [
        "paste text: hello from Jarvis",
        "human write: hello from Jarvis",
        "write a paragraph about Jarvis and type it",
        "compose a quick project intro in google docs",
        "Writing into the focused app controls the keyboard or clipboard and stays HIGH_RISK/approval-gated.",
    ],
    "fun": [
        "joke",
        "tell me a joke",
        "tell me something funny",
        "flip a coin",
        "toss a coin",
        "roll a die",
        "roll a pair of dice",
        "roll 2 dice",
        "roll 2d6",
        "pick a random number",
        "pick a number between one and ten",
        "choose between pizza and sushi",
        "help me decide between pizza and sushi",
        "dad joke",
        "make me laugh",
        "Fun tools are lightweight and read-only unless a request also asks Jarvis to write or send something.",
    ],
    "currency": [
        "convert 100 USD to KRW",
        "usd to krw",
        "100 dollars in won",
        "100 usd krw",
        "how much is 50 euros in dollars",
        "what is 100 euros in dollars",
        "convert 1,000 yen to GBP",
        "Currency conversion is LOCAL_SAFE, but it may call the configured public rate service.",
    ],
    "weather": [
        "what's the weather",
        "weather in Tokyo",
        "is it going to rain",
        "do I need an umbrella today",
        "Weather lookup is LOCAL_SAFE, but it may call the configured public weather service.",
    ],
    "news": [
        "what is the news",
        "headlines",
        "news about Korea",
        "Korea news",
        "AI news today",
        "what is happening in the world",
        "News lookup is LOCAL_SAFE, but it may call the configured public RSS/news service.",
    ],
    "markets": [
        "market update",
        "markets overview in Korean",
        "stocks today",
        "what is bitcoin worth",
        "what's BTC at",
        "crypto price",
        "stock price of AAPL",
        "AAPL price",
        "AAPL stock",
        "Market price lookups are LOCAL_SAFE, but they may call configured public market-data services.",
        "Market outputs are informational only, not financial advice.",
    ],
    "translation": [
        "translate hello to Korean",
        "how do you say thank you in Korean",
        "how to say good morning in Korean",
        "Korean for good morning",
        "English for 사랑",
        "say good morning in Korean",
        "what is 사랑 in English",
        "what does 사랑 mean in English",
        "translate 안녕 to English",
        "Translation is LOCAL_SAFE, but it may call the configured translation service.",
        "Do not put secrets, private messages, or sensitive personal data into translation requests.",
    ],
    "calendar": [
        "list calendars",
        "what's on my calendar today",
        "what is on my schedule today",
        "what am I doing today",
        "schedule today",
        "show my calendar today",
        "am I free tomorrow afternoon",
        "free today",
        "schedule lunch tomorrow at noon",
        "schedule PTO all day tomorrow",
        "move event evt123 to June 20 at 2pm",
        "rename event evt123 to Lunch with Sam",
        "move my 3pm to 4pm",
        "Calendar creates, deletes, and updates are HIGH_RISK and stay approval-gated.",
        "Fuzzy calendar edits require an exact event id before Jarvis changes anything.",
    ],
    "automation": [
        "morning startup",
        "save morning startup",
        "scheduler context refresh",
        "daily plan",
        "weekly review context",
        "weekly review prompt preview",
        "weekly review",
        "schedule assistant basics",
        "resume job State Snapshot",
        "resume job Conversation Compaction",
        "schedule daily brief",
        "schedule inbox ingest",
        "schedule file digest",
        "list scheduled jobs",
        "run job Weekly Review now",
        "run morning brief now",
        "Schedule changes, reminders, and job runs stay approval-aware and audited before any external or time-based side effect.",
    ],
    "desktop": [
        "list voices",
        "voice setup check",
        "voice capture privacy",
        "voice reply preview: Jarvis is ready",
        "spoken turn rehearsal: run command python3 --version",
        "voice file transcription plan: /path/to/audio.m4a",
        "voice note plan: /path/to/audio.m4a",
        "voice audio file gate: /path/to/audio.m4a consent=true",
        "voice note gate: /path/to/audio.m4a consent=true",
        "voice audio file transcribe: /path/to/audio.m4a consent=true receipt_id=voice-file-...",
        "photo intake plan: /path/to/receipt.png",
        "review this photo",
        "what does this receipt say",
        "ocr image: /path/to/receipt.png",
        "voice input plan push-to-talk",
        "voice transcript review: run command python3 --version",
        "voice confirmation: remember that Jarvis should ask before acting on speech",
        "voice confirmation receipt: run command python3 --version confirmed=true",
        "voice confirmation audit ledger: run command python3 --version; confirmed=true; privacy_receipt_id=<receipt>; receipt_id=<receipt>; receipt_nonce=<nonce>",
        "voice route gate: run command python3 --version confirmed=true",
        "voice command lifecycle: run command python3 --version",
        "voice command cockpit: run command python3 --version confirmed=true",
        "voice action audit: run command python3 --version confirmed=true",
        "voice execution handoff: run command python3 --version confirmed=true",
        "voice post-run closure: run command python3 --version; confirmed=true; verification reviewed; verification_receipt_sha256=<hash>; post health reviewed; execution_health_sha256=<hash>; post audit reviewed; execution_audit_sha256=<hash>; learning reviewed; after_action_learning_sha256=<hash>",
        "voice cycle ledger: run command python3 --version; confirmed=true; verification reviewed; verification_receipt_sha256=<hash>; post health reviewed; execution_health_sha256=<hash>; post audit reviewed; execution_audit_sha256=<hash>; learning reviewed; after_action_learning_sha256=<hash>",
        "speak hello",
        "stop Jarvis",
        "computer control status",
        "computer readiness: open settings and check battery",
        "computer task plan: open settings and check battery",
        "computer action packet: click x 100 y 200 expectation battery settings opens",
        "approved screen observation receipt: expectation battery settings opens; observation battery settings panel is visible; source approved_screenshot; observation id obs-7; screenshot path /tmp/jarvis_oav_before.png; captured at 2026-06-09T10:00:00+09:00; redaction reviewed safe; approval 7",
        "screen observation freshness: expectation battery settings opens; observation battery settings panel is visible; source approved_screenshot; observation id obs-7; screenshot path /tmp/jarvis_oav_before.png; captured at 2026-06-09T10:00:00+09:00; current time 2026-06-09T10:03:00+09:00; max age 300; redaction reviewed safe; approval 7",
        "screen observation confidence: expectation battery settings opens; observation battery settings panel is visible; source approved_screenshot",
        "screen vision prompt preview: expectation battery settings opens; observation battery settings panel is visible; source approved_screenshot; observation id obs-7; screenshot path /tmp/jarvis_oav_before.png; captured at 2026-06-09T10:00:00+09:00; redaction reviewed safe; approval 7",
        "screen vision model review: expectation battery settings opens; observation battery settings panel is visible; source approved_screenshot; observation id obs-7; screenshot path /tmp/jarvis_oav_before.png; captured at 2026-06-09T10:00:00+09:00; redaction reviewed safe; approval 7; consent=true",
        "screen verification contract: expectation battery settings opens; observation battery settings panel is visible",
        "observe act verify proof: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot",
        "oav route lock: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified",
        "oav approval bridge: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22",
        "oav cockpit: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22",
        "oav final review: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22; audit execution audit passed; health execution health passed; review operator reviewed final packet",
        "oav action audit: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22; audit execution audit passed; health execution health passed; review operator reviewed final packet",
        "oav execution handoff: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22; audit execution audit passed; health execution health passed; review operator reviewed final packet",
        "oav post-run closure: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22; audit execution audit passed; health execution health passed; review operator reviewed final packet; verification verification receipt 22 verified; post health execution health passed; post audit execution audit passed; learning after-action learning reviewed",
        "oav cycle ledger: action click; x 100; y 200; expectation battery settings opens; observation battery settings opens; source approved_screenshot; after battery settings opens; approval readiness reviewed; approval packet reviewed; approval chain proof passed; approved rerun verified; approval 7; approved run 22; verification receipt 22; audit execution audit passed; health execution health passed; review operator reviewed final packet; verification verification receipt 22 verified; post health execution health passed; post audit execution audit passed; learning after-action learning reviewed",
        "enable computer control",
        "observe screen",
    ],
    "code": [
        "run command python3 --version",
        "list files in .",
        "read README.md",
        "read file README.md",
        "find my receipt file",
        "find files README in .",
        "approval packet 1",
    ],
}


HELP_TOPIC_ALIASES = {
    "cockpit": "control",
    "capability cockpit": "control",
    "control plane": "control",
    "control-plane": "control",
    "control_plane": "control",
    "dashboard": "control",
    "health": "control",
    "status": "control",
    "channel health": "control",
    "channel status": "control",
    "live proof": "control",
    "live proofs": "control",
    "live test": "control",
    "live tests": "control",
    "risk matrix": "control",
    "trust": "control",
    "worker": "control",
    "workers": "control",
    "agent": "control",
    "agents": "control",
    "orchestration": "control",
    "internal orchestration": "control",
    "approval queue": "approvals",
    "pending approval": "approvals",
    "pending approvals": "approvals",
    "redos": "safety",
    "regex dos": "safety",
    "regex safety": "safety",
    "frozen redos": "safety",
    "frozen routing": "safety",
    "frozen routing risk": "safety",
    "send call routing risk": "safety",
    "planner input guard": "safety",
    "input length guard": "safety",
    "long input safety": "safety",
    "long command safety": "safety",
    "long message redos": "safety",
    "daily brief": "automation",
    "daily briefing": "automation",
    "morning brief": "automation",
    "morning briefing": "automation",
}


def _resolve_help_topic(topic: str) -> str:
    normalized = " ".join(str(topic or "").strip().lower().replace("_", " ").replace("-", " ").split())
    if not normalized:
        return ""
    exact = HELP_TOPIC_ALIASES.get(normalized, normalized)
    if exact in HELP_SECTIONS:
        return exact

    candidates = sorted(set(HELP_SECTIONS) | set(HELP_TOPIC_ALIASES))
    matches = difflib.get_close_matches(normalized, candidates, n=1, cutoff=0.82)
    if not matches:
        return normalized
    match = matches[0]
    return HELP_TOPIC_ALIASES.get(match, match)


def _safe_metadata(**extra: Any) -> dict[str, Any]:
    metadata = {
        "calls_model": False,
        "calls_external_service": False,
        "executes_tools": False,
        "reads_personal_data": False,
        "reads_private_data": False,
        "executes_side_effect": False,
        "external_side_effect": False,
        "writes_files": False,
        "writes_database": False,
        "writes_memory": False,
        "writes_notes": False,
        "queues_approval": False,
        "requires_approval": False,
        "controls_computer": False,
        "speaks": False,
        "completes_tasks": False,
        "authorizes_execution": False,
        "authorizes_completion_claim": False,
        "approval_granted": False,
    }
    metadata.update(extra)
    return metadata


def _safe_text(value: Any, *, limit: int = 180) -> str:
    text = " ".join(str(value or "").split())
    text = LOCAL_PATH_RE.sub("<local-path>", text)
    if len(text) > limit:
        return text[: max(0, limit - 1)].rstrip() + "…"
    return text


def _help_boundaries() -> dict[str, bool]:
    return {
        "read_only": True,
        "calls_model": False,
        "calls_external_service": False,
        "executes_tools": False,
        "reads_personal_data": False,
        "reads_private_data": False,
        "executes_side_effect": False,
        "external_side_effect": False,
        "writes_files": False,
        "writes_database": False,
        "writes_memory": False,
        "writes_notes": False,
        "queues_approval": False,
        "requires_approval": False,
        "controls_computer": False,
        "speaks": False,
        "completes_tasks": False,
        "authorizes_execution": False,
        "authorizes_completion_claim": False,
        "approval_granted": False,
    }


def _help_handoff(*, topic: str, entries: list[str] | None = None, index: bool = False) -> dict[str, Any]:
    examples = list(entries or [])
    if index:
        section_rows = [
            {
                "topic": name,
                "entries": len(items),
                "preview": [_safe_text(item) for item in items[:3]],
                "command": f"help {name}",
            }
            for name, items in sorted(HELP_SECTIONS.items())
        ]
        entry_count = sum(row["entries"] for row in section_rows)
        preview = [_safe_text(item) for item in HELP_SECTIONS.get("core", [])[:3]]
    else:
        section_rows = [
            {
                "topic": topic,
                "entries": len(examples),
                "preview": [_safe_text(item) for item in examples[:5]],
                "command": f"help {topic}",
            }
        ]
        entry_count = len(examples)
        preview = [_safe_text(item) for item in examples[:8]]
    return {
        "source": "jarvis_help",
        "topic": topic,
        "index": index,
        "sections": len(section_rows),
        "entries": entry_count,
        "topics": sorted(HELP_SECTIONS),
        "section_rows": section_rows,
        "example_preview": preview,
        "next_commands": ["help", "capability map", "tool search: approvals", "risk matrix", "safety status"],
        "ready_for_operator": True,
        "changed": [],
        "authorizes_execution": False,
        "authorizes_completion_claim": False,
        "approval_granted": False,
        "content_in_handoff": False,
        "boundaries": _help_boundaries(),
    }


def _help_metadata(*, topic: str, entries: list[str] | None = None, index: bool = False) -> dict[str, Any]:
    handoff = _help_handoff(topic=topic, entries=entries, index=index)
    return _safe_metadata(
        topic=topic,
        sections=handoff["sections"],
        entries=handoff["entries"],
        help_handoff=handoff,
        help_handoff_ready=True,
        help_status="ok",
    )


def jarvis_help(args: dict[str, Any]) -> ToolResult:
    topic = _resolve_help_topic(str(args.get("topic") or ""))
    if topic and topic in HELP_SECTIONS:
        lines = [f"Jarvis help: {topic}"]
        lines.extend(f"- {item}" for item in HELP_SECTIONS[topic])
        return ToolResult("jarvis_help", True, "\n".join(lines), _help_metadata(topic=topic, entries=HELP_SECTIONS[topic]))

    lines = ["Jarvis help topics: " + ", ".join(sorted(HELP_SECTIONS))]
    lines.extend(["", describe_capabilities()])
    for name, examples in HELP_SECTIONS.items():
        lines.append(f"\n## {name.title()}")
        lines.extend(f"- {item}" for item in examples[:4])
    return ToolResult("jarvis_help", True, "\n".join(lines), _help_metadata(topic="index", index=True))
